from unittest import TestCase

from twitterpibot.schedule.WeatherScheduledTask import WeatherScheduledTask

__author__ = 'andrewtatham'


class TestWeatherScheduledTask(TestCase):
    def test_parse(self):
        fail_tweets = [
            "@Tmckinnin Sorry, we're not sure where you mean. Try using a postcode or including the county. Weather homepage: https://t.co/KCtAKSzXgW",
            "@BoshGobran Sorry, we're not sure where you mean. Try using a postcode or including the county. Weather homepage: https://t.co/1PcFSzPrtr",
            "@BoshGobran Sorry, we need a place and a time. Try including a day. For a 9-day forecast for that location visit: https://t.co/bET6j1j580",
            "@bptd1234 Sorry, we're not sure where you mean. Try using a postcode or including the county. Weather homepage: https://t.co/qpUEH4WlPJ",
            "@Mindyerown Sorry, we're not sure where you mean. Try using a postcode or including the county. Weather homepage: https://t.co/aQOxCXc5zP",
            "@TGOTWEETS_ Sorry, we're not sure where you mean. Try using a postcode or including the county. Weather homepage: https://t.co/LOtp0vEmvh",

            "@Tmckinnin Sorry, that's a bit too far ahead for the Weatherbot to see, but for a 9-day forecast visit: https://t.co/UVYBTIe7vk",
            "@Kingsbury_Geo Sorry, that's a bit too far ahead for the Weatherbot to see, but for a 9-day forecast visit: https://t.co/B5JJIgkRRL",

            "@TGOTWEETS_ Sorry, we need a place and a time. Try including a day. For a 9-day forecast for that location visit: https://t.co/x1NUyKnScM",
            "@just_dizzyb Sorry, we need a place and a time. Try including a day. For a 9-day forecast for that location visit: https://t.co/Nmx7flOyEw",
            "@susiej1424 Sorry, we need a place and a time. Try including a day. For a 9-day forecast for that location visit: https://t.co/ikZM1T0g6H",
            "@zeusdamoose Sorry, we need a place and a time. Try including a day. For a 9-day forecast for that location visit: https://t.co/UWlvQkQ05k",
            "@danjwilkinson Sorry, we need a place and a time. Try including a day. For a 9-day forecast for that location visit: https://t.co/fHJ5xjb7em",
            "@Tmckinnin Sorry, we need a place and a time. Try including a day. For a 9-day forecast for that location visit: https://t.co/eM3AE89eNB",

            "@TGOTWEETS_ Sorry, the Weatherbot can only handle one location at a time, try asking again. Weather homepage: https://t.co/4WzDqaz4hm",
            "@paulyd_81303 Sorry, the Weatherbot can only handle one date at a time, try asking again. Weather homepage: https://t.co/ITPnXFLSKP",
            "@FedeGeno1 Sorry, the Weatherbot can only handle one date at a time, try asking again. Weather homepage: https://t.co/wqk8LjwOWx",

            "@ruechampagne The time you asked for appears to be in the past. For the latest forecast visit: https://t.co/8bah9zFrdw",
            "@richardkendall The time you asked for appears to be in the past. For the latest forecast visit: https://t.co/wCjveqSSoS",
            "@KimExplain Sorry, the Weatherbot can only handle one date at a time, try asking again. Weather homepage: https://t.co/OJ6W3NMTJY",
            "@maysie06 Sorry, the Weatherbot can only handle one location at a time, try asking again. Weather homepage: https://t.co/T8tYQOiD5X",
            "@_singsun Sorry, we need a place and a time. Try including a day. For a 9-day forecast for that location visit: https://t.co/kn60Wjt0I3",
            "@JackTurk Sorry, we need a place and a time. Try including a day. For a 9-day forecast for that location visit: https://t.co/0SbMf0icVt",
            "@glebefootball Sorry, the Weatherbot can only handle one date at a time, try asking again. Weather homepage: https://t.co/B7t5l0SKeb",
            "@homesickgeordie Sorry, the Weatherbot can only handle one date at a time, try asking again. Weather homepage: https://t.co/THa9qWbiWr",
            "@burt13 Sorry, we need a place and a time. Try including a day. For a 9-day forecast for that location visit: https://t.co/0y6LYjvwTU",
            "@EmmaLSaxton Sorry, the Weatherbot can only handle one date at a time, try asking again. Weather homepage: https://t.co/K1iMh0A7pn",
            "@fest64 Sorry, we're not sure where you mean. Try using a postcode or including the county. Weather homepage: https://t.co/zTSPfzvS6X",
            "@Tmckinnin Sorry, we're not sure where you mean. Try using a postcode or including the county. Weather homepage: https://t.co/aOGZVnpyUR",
            "@EnglishSammie Sorry, the Weatherbot can only handle one date at a time, try asking again. Weather homepage: https://t.co/ouTnr9pMHn",
            "@Tmckinnin Sorry, we're not sure where you mean. Try using a postcode or including the county. Weather homepage: https://t.co/uBpQ2VOXwC",
            "@spiderdan4 Sorry, we're not sure where you mean. Try using a postcode or including the county. Weather homepage: https://t.co/begq206B2u",
            "@spiderdan4 Sorry, we're not sure where you mean. Try using a postcode or including the county. Weather homepage: https://t.co/aQo7jZV7AI",
            "@ArianaNGiorgi Sorry, we need a place and a time. Try including a day. For a 9-day forecast for that location visit: https://t.co/5uEMvK4kSi",
            "@Abdulqani3 Sorry, we need a place and a time. Try including a day. For a 9-day forecast for that location visit: https://t.co/eRRZMFQ4ml",
            "@sinclairpirie Sorry, we're not sure where you mean. Try using a postcode or including the county. Weather homepage: https://t.co/AOLEqtkRN8",
            "@Tmckinnin Sorry, that's a bit too far ahead for the Weatherbot to see, but for a 9-day forecast visit: https://t.co/ExLVX76X4k",
            "@Tmckinnin Sorry, we're not sure where you mean. Try using a postcode or including the county. Weather homepage: https://t.co/KuX8QP2EJi",
            "@Tmckinnin Sorry, we're not sure where you mean. Try using a postcode or including the county. Weather homepage: https://t.co/KqzUkyk14m",
            "@lukie57575757 Sorry, we need a place and a time. Try including a day. For a 9-day forecast for that location visit: https://t.co/xkYgSYYTpI",
            "@Tmckinnin Sorry, we need a place and a time. Try including a day. For a 9-day forecast for that location visit: https://t.co/pToGXSubLk",
            "@HenryDarling3 Sorry, the Weatherbot can only handle one location at a time, try asking again. Weather homepage: https://t.co/uPl9rIft8c",
            "@mumoss Sorry, we're not sure where you mean. Try using a postcode or including the county. Weather homepage: https://t.co/f5OxMSwA2S",
            "@marilyn29823417 Sorry, that's a bit too far ahead for the Weatherbot to see, but for a 9-day forecast visit: https://t.co/ebtiZ8gjrb",
            "@marilyn29823417 Sorry, that's a bit too far ahead for the Weatherbot to see, but for a 9-day forecast visit: https://t.co/yv2i3PREfd",
            "@mc0uk We found more than one location with that name; try including a postcode or county. Weather homepage: https://t.co/0S5OT2R9oj",
            "@D_Lofty We found more than one location with that name; try including a postcode or county. Weather homepage: https://t.co/iVl9VMkqqM",
            "@StevenSaul We found more than one location with that name; try including a postcode or county. Weather homepage: https://t.co/dQFhejDQWB",
            "@leedamastr We found more than one location with that name; try including a postcode or county. Weather homepage: https://t.co/NTqeY8VKiC",
        ]

        tweets = [
            "@davidp64 Our forecast shows temperatures up to 10°C, light rain and a little wind.  https://t.co/f5vqvO2Qfl",
            "@emmatown4 We're looking at temperatures up to 12°C, heavy rain and a little wind.  https://t.co/5hWfEVsrJf",
            "@Tmckinnin We should see temperatures up to 8°C, light rain and a little wind.  https://t.co/n4ZizVKQKD",
            "@Tmckinnin We're expecting temperatures up to 10°C, white cloud and a little wind.  https://t.co/Lw7juJi4bz",
            "@mrsvickyclark We're likely to see temperatures up to 11°C, light rain and a little wind.  https://t.co/k0N3MZ42Qw",
            "@bptd1234 We should see temperatures up to 12°C, heavy rain showers and a little wind.  https://t.co/FepQqtTg0V",
            "@andrewtathampi We're expecting temperatures up to 11°C, white cloud and a little wind.  https://t.co/1PbqvSRm5M",
            "@JackTurk We're expecting temperatures up to 15°C, sunny intervals and a little wind.  https://t.co/hnjEna3u69",
            "@rachaelhamson We're expecting temperatures up to 12°C, white cloud and a little wind.  https://t.co/2FnqS16x5y",
            "@NicholasHayman Our forecast shows temperatures up to 13°C, light rain and a little wind.  https://t.co/0tFoi4NOyv",
            "@BoshGobran Our forecast shows temperatures as low as 6°C, and grey cloud.  https://t.co/2FsI2NeY9m",
            "@ruechampagne We're looking at temperatures up to 10°C, heavy rain and a little wind.  https://t.co/5rVCCf6nab",
            "@tommydoors Our forecast shows temperatures up to 10°C, light rain and a little wind.  https://t.co/lfpMgRt3L3",
            "@Tmckinnin We're looking at temperatures up to 8°C, heavy rain and a little wind.  https://t.co/DTbW8u3FFM",
            "@Tmckinnin We're expecting temperatures up to 10°C, white cloud and a little wind.  https://t.co/vkJg7UmbRO",
            "@Tmckinnin We're likely to see temperatures up to 10°C, grey cloud and a little wind.  https://t.co/5tDH7lLFmx",
            "@bptd1234 Our forecast shows temperatures up to 14°C, sunny intervals and a little wind.  https://t.co/jnf429h150",
            "@HenryDarling3 We should see temperatures up to 9°C, white cloud and a little wind.  https://t.co/tGNtniXgih",
            "@andrewtathampi Our forecast shows temperatures up to 13°C, sunny intervals and a little wind.  https://t.co/c0gD3KjJY7",
            "@samanthawilso10 We're looking at temperatures up to 13°C, sunny intervals and a little wind.  https://t.co/FWNlIm5vMf",
            "@HenryDarling3 We should see temperatures as low as 5°C, and grey cloud.  https://t.co/HCJ6pdEySl",
            "@Tmckinnin We're expecting temperatures up to 11°C, grey cloud and a little wind.  https://t.co/FKPJimCpIO",
            "@Tmckinnin We're likely to see temperatures up to 10°C, light rain and a strong breeze.  https://t.co/grv9BhKcKW",
            "@jawline_jen We're likely to see temperatures up to 17°C, sunny intervals and a little wind.  https://t.co/oonBa1Dao0",
            "@HenryDarling3 We're looking at temperatures up to 10°C, white cloud and a little wind.  https://t.co/j3CzMHxWtK",
            "@susiej1424 We're likely to see temperatures up to 14°C, sunny intervals and a little wind.  https://t.co/4PHUct6IOE",
            "@andrewtathampi We're likely to see temperatures up to 10°C, heavy rain and a little wind.  https://t.co/POu7CX4fav",
            "@JackTurk We're looking at temperatures up to 12°C, sunny intervals and a little wind.  https://t.co/9UhZEEHjva",
            "@BoroGarden Our forecast shows temperatures up to 10°C, light rain and a little wind.  https://t.co/VVMAHaXxmy",
            "@HenryDarling3 We're likely to see temperatures up to 10°C, light rain and a little wind.  https://t.co/P15rsXJBpV",
            "@sassamoose We should see temperatures up to 14°C, light rain showers and a little wind.  https://t.co/Ov9exQDzWt",
            "@clousmithy We should see temperatures up to 10°C, heavy rain and a little wind.  https://t.co/WjrTiqfaoj",
            "@paulyd_81303 We're looking at temperatures up to 8°C, light rain and a little wind.  https://t.co/hDgGaWwURP",
            "@Mindyerown Our forecast shows temperatures up to 10°C, white cloud and a little wind.  https://t.co/geBtDd3ijD",
            "@paulyd_81303 We're expecting temperatures up to 10°C, light rain and a little wind.  https://t.co/929r7CA8jX",
            "@g0hjq We should see temperatures up to 11°C, white cloud and a little wind.  https://t.co/IzMtfHTjQg",
            "@danjwilkinson We're expecting temperatures up to 13°C, sunny intervals and a little wind.  https://t.co/6u3YJ8xNpm",
            "@SkegnessWeb We should see temperatures up to 13°C, white cloud and a little wind.  https://t.co/UkjqOQbelI",
            "@IAWHD We're expecting temperatures up to 12°C, white cloud and a little wind.  https://t.co/tEHTzNOvoO",
            "@3onner We're expecting temperatures up to 13°C, sunny intervals and a little wind.  https://t.co/KYzB56huq9",
            "@Yatzy1970 We should see temperatures up to 14°C, and white cloud.  https://t.co/P0rZKF9D9q",
            "@barstep Our forecast shows temperatures up to 11°C, light rain and a little wind.  https://t.co/BNH2d3wPaY",
            "@Tmckinnin Our forecast shows temperatures up to 9°C, heavy rain and a strong breeze.  https://t.co/WTHFbPtHek",
            "@Tmckinnin We're looking at temperatures up to 11°C, white cloud and a strong breeze.  https://t.co/HGolE36Wrc",
            "@mrlonthames We're looking at temperatures up to 13°C, white cloud and a little wind.  https://t.co/cvkTi5tgvy",
            "@xoxDawniexox We're looking at temperatures up to 11°C, white cloud and a little wind.  https://t.co/OYtyC3rJUA",
            "@JohnnyfromDonny We're looking at temperatures up to 11°C, white cloud and a little wind.  https://t.co/yzMdO9lwD3",
            "@FedeGeno1 We should see temperatures up to 11°C, heavy rain and a little wind.  https://t.co/LZRbCtuZT4",
            "@MarkTee83 We're likely to see temperatures up to 7°C, white cloud and a strong breeze.  https://t.co/yX1Ha5nqCa",
            "@JackTurk Our forecast shows temperatures up to 12°C, and light rain.  https://t.co/KVRGoyJR4z",
            "@andrewtathampi We should see temperatures up to 14°C, white cloud and a strong breeze.  https://t.co/ewacJ88VlC",
            "@just_dizzyb We should see temperatures as low as 8°C, and clear skies.  https://t.co/aZfP6sbW1N",
            "@seandmc_ Our forecast shows temperatures up to 14°C, white cloud and a strong breeze.  https://t.co/6z9EFZz6c1",
            "@JonWitts1 Our forecast shows temperatures up to 10°C, heavy rain and a little wind.  https://t.co/DB9ckwfJ5N",
            "@awaithelp We're looking at temperatures up to 14°C, white cloud and a strong breeze.  https://t.co/h7ZYlAmyKA",
            "@christinaclarke We're looking at temperatures up to 16°C, white cloud and a little wind.  https://t.co/z64pmbFMxA",
            "@russt81 We should see temperatures up to 13°C, white cloud and a strong breeze.  https://t.co/xcsYTJ1HHI",
            "@awaithelp We're expecting temperatures up to 12°C, sunny intervals and a little wind.  https://t.co/Jc6WIR5BB3",
            "@nhstn Our forecast shows temperatures up to 11°C, white cloud and a strong breeze.  https://t.co/Op1DMpPUHe",
            "@nhstn We should see temperatures up to 11°C, sunny intervals and a strong breeze.  https://t.co/dcvd3yApzh",
            "@Lilmissdanni Our forecast shows temperatures up to 12°C, white cloud and a little wind.  https://t.co/WnweOuIExT",
            "@JonWitts1 Our forecast shows temperatures as low as 2°C, and partial cloud.  https://t.co/KWgv1DQSND",
            "@JackTurk We're expecting temperatures up to 11°C, white cloud and a strong breeze.  https://t.co/NQTKfGgcQg",
            "@chrsgrms Our forecast shows temperatures up to 11°C, sunny intervals and a strong breeze.  https://t.co/8GpoFN2La5",
            "@DoddsDouglas We should see temperatures up to 11°C, white cloud and a strong breeze.  https://t.co/h3nJbBh5eK",
            "@ArianaNGiorgi We're likely to see temperatures up to 13°C, white cloud and a little wind.  https://t.co/tyN7lHO8bC",
            "@Tmckinnin We should see temperatures up to 12°C, sunny intervals and a little wind.  https://t.co/4lf0ehsB2w",
            "@Tmckinnin We're expecting temperatures up to 10°C, white cloud and a little wind.  https://t.co/2vVdaCWAAG",
            "@MonicaRose60 We're expecting temperatures up to 11°C, white cloud and a strong breeze.  https://t.co/0u2HTEothn",
            "@MonicaRose60 Our forecast shows temperatures up to 12°C, sunny intervals and a little wind.  https://t.co/szwNdsXjkT",
            "@MonicaRose60 We should see temperatures up to 10°C, white cloud and a little wind.  https://t.co/l52fTvhRHP",
            "@mrsvickyclark We're looking at temperatures up to 9°C, sunny intervals and a little wind.  https://t.co/V8xOhdddZu",
            "@ScotAlly We're expecting temperatures up to 8°C, white cloud and a strong breeze.  https://t.co/Z6rey2XExk",
            "@sunnyjim123 We're expecting temperatures up to 13°C, white cloud and a strong breeze.  https://t.co/OLuN96U2U6",
            "@spiderdan4 We should see temperatures up to 7°C, light rain and a little wind.  https://t.co/P6r6KQA8yd",
            "@Tmckinnin We're likely to see temperatures up to 11°C, white cloud and a little wind.  https://t.co/zIJUMlQNhv",
            "@andrewtathampi We're expecting temperatures up to 12°C, white cloud and a little wind.  https://t.co/HI40XJzKYK",
            "@sinclairpirie We're likely to see temperatures up to 7°C, white cloud and a little wind.  https://t.co/4zxqOUcm2u",
            "@BrenchleyLion We should see temperatures as low as 4°C, and partial cloud.  https://t.co/EbAc0zAt66",
            "@Tmckinnin Our forecast shows temperatures up to 12°C, sunshine and a little wind.  https://t.co/dx40bLU5IC",
            "@Tmckinnin We're expecting temperatures up to 9°C, light rain and a little wind.  https://t.co/GwzX7xCKna",
            "@Tmckinnin We're expecting temperatures up to 11°C, white cloud and a little wind.  https://t.co/4AFgig7Gzs",
            "@Tmckinnin We should see temperatures up to 12°C, white cloud and a strong breeze.  https://t.co/4zQB5jRZtF",
            "@RosieCampbell Our forecast shows temperatures up to 11°C, white cloud and a little wind.  https://t.co/JAJuEHTV4n",
            "@rodgerkibble We should see temperatures up to 9°C, light rain showers and a strong breeze.  https://t.co/SfNRrlJb0a",
            "@andrewtathampi We should see temperatures up to 11°C, light rain and a little wind.  https://t.co/0tRVmBE3Ir",
            "@louisemartin25 Our forecast shows temperatures up to 8°C, light rain showers and a little wind.  https://t.co/7YDy8ikGvg",
            "@callumeakins We're likely to see temperatures up to 8°C, light rain showers and a little wind.  https://t.co/wyNnoa9kSk",
            "@HenryDarling3 We're expecting temperatures up to 9°C, light rain and a little wind.  https://t.co/PWze12sOD7",
            "@ScotAlly We're likely to see temperatures up to 7°C, heavy rain and a little wind.  https://t.co/CDTBtSzctl",
            "@louisemartin25 Our forecast shows temperatures up to 8°C, white cloud and a little wind.  https://t.co/wuHt0OCjhV",
            "@Tmckinnin We're expecting temperatures up to 13°C, white cloud and a strong breeze.  https://t.co/c0CrawSKWW",
            "@Tmckinnin We're looking at temperatures up to 8°C, light rain and a strong breeze.  https://t.co/AuelTQuurs",
            "@meatloaf1333 We should see temperatures up to 7°C, heavy rain showers and a strong breeze.  https://t.co/RCmERXMn8C",
            "@rodgerkibble We're likely to see temperatures up to 9°C, heavy rain showers and a strong breeze.  https://t.co/Do7zKh7qER",
            "@lukie57575757 We're looking at temperatures up to 9°C, light rain and a strong breeze.  https://t.co/mpgcFkDtwv",
            "@JackTurk Our forecast shows temperatures up to 10°C, white cloud and a strong breeze.  https://t.co/FkG2SnNBz4",
            "@andrewtathampi We're looking at temperatures up to 9°C, heavy rain showers and a strong breeze.  https://t.co/39lfVlX8hd",
            "@JackTurk We're expecting temperatures up to 10°C, white cloud and a strong breeze.  https://t.co/4pG0lv7Mym",
            "@HenryDarling3 We should see temperatures up to 7°C, heavy rain showers and a strong breeze.  https://t.co/PRKnvZKAuu",
            "@chrisukstevens We're likely to see temperatures up to 8°C, light rain and a strong breeze.  https://t.co/PH99EZfybD",
            "@mumoss We should see temperatures up to 13°C, light rain and a strong breeze.  https://t.co/t3A316D7ja",
            "@rodgerkibble We're likely to see temperatures up to 10°C, light rain showers and a strong breeze.  https://t.co/nWpemya474",
            "@Tmckinnin We're expecting temperatures up to 12°C, white cloud and a little wind.  https://t.co/t2K0mtZkl3",
            "@marilyn29823417 We're expecting temperatures up to 9°C, heavy rain and a strong breeze.  https://t.co/BrJCp8W1P0",
            "@andrewtathampi Our forecast shows temperatures up to 12°C, sunny intervals and a strong breeze.  https://t.co/7FZuI2h9ic",
            "@JackTurk Our forecast shows temperatures up to 9°C, white cloud and a strong breeze.  https://t.co/cIO3Y4WsZr",
            "@JackTurk We're looking at temperatures up to 12°C, sunshine and a little wind.  https://t.co/UZ2XoJgOf0",
            "@StevenSaul We're expecting temperatures up to 12°C, sunny intervals and a strong breeze.  https://t.co/lxmiwToRIl",
            "@maysie06 Our forecast shows temperatures up to 13°C, white cloud and a little wind.  https://t.co/74SlBc1VJ6",
            "@Basher2010 We're expecting temperatures up to 10°C, light rain and a strong breeze.  https://t.co/EVgCWWmxU9",
            "@sharpjeff2000 Our forecast shows temperatures up to 9°C, light rain and a little wind.  https://t.co/TpN1AA08sQ",
            "@homesickgeordie We're looking at temperatures up to 9°C, grey cloud and a little wind.  https://t.co/qx8hJNdr83",
            "@OiClarkson Our forecast shows temperatures up to 9°C, grey cloud and a little wind.  https://t.co/4kZZ1kSJxE",
            "@Garry_Nixon Our forecast shows temperatures up to 10°C, white cloud and a little wind.  https://t.co/8QsyLyCmTP",
            "@anandbalaspadm We're looking at temperatures up to 13°C, white cloud and a little wind.  https://t.co/KdbOtKwrZv",
            "@HenryDarling3 We're looking at temperatures up to 11°C, sunny intervals and a little wind.  https://t.co/AM7bEIrzF1",
            "@glebefootball We're looking at temperatures up to 13°C, sunny intervals and a little wind.  https://t.co/G2m3vx0zCv",
            "@cestriankeef We should see temperatures up to 12°C, grey cloud and a little wind.  https://t.co/WjkqaJZdzi",
            "@mumoss We should see temperatures up to 15°C, white cloud and a little wind.  https://t.co/A0XAohd5DR",
            "@meatloaf1333 We're expecting temperatures up to 11°C, light rain showers and a little wind.  https://t.co/QsDfWGDfHm",
            "@Tmckinnin We're looking at temperatures up to 10°C, heavy rain and a little wind.  https://t.co/gNRkdopBIs",
            "@Thorntons_ We should see temperatures as low as 6°C, and white cloud.  https://t.co/Ga17drJMdZ",
            "@danJW17 We're likely to see temperatures up to 11°C, white cloud and a strong breeze.  https://t.co/VvdnTk3tUW",
            "@andrewtathampi We're likely to see temperatures up to 12°C, light rain and a little wind.  https://t.co/1CPtCb2Bx6",
            "@Mrs_L_James We're expecting temperatures up to 10°C, and white cloud.  https://t.co/08MebLSioH",
            "@emmatown4 We're expecting temperatures as low as 8°C, and light rain.  https://t.co/RRHsQFUTS8",
            "@Leighannesmiffy We're likely to see temperatures up to 13°C, white cloud and a little wind.  https://t.co/UfAEQ2Og6x",
            "@EmmaLSaxton We're looking at temperatures up to 13°C, white cloud and a little wind.  https://t.co/rcHBmXcayo",
            "@EnglishSammie We're likely to see temperatures as low as 8°C, and light rain.  https://t.co/6607Roe0Iz",
            "@tommymdonald185 We should see temperatures up to 11°C, white cloud and a little wind.  https://t.co/Jj7ZU5GtwU",
            "@tommymdonald185 We're looking at temperatures up to 11°C, white cloud and a little wind.  https://t.co/6PWNVCHXcc",
            "@edboydenphotos We're looking at temperatures up to 10°C, light rain and a little wind.  https://t.co/K6qRXHPgnl",
            "@edboydenphotos We should see temperatures up to 11°C, light rain and a little wind.  https://t.co/WWWDTotUr1",
            "@Lilmissdanni Our forecast shows temperatures up to 13°C, white cloud and a little wind.  https://t.co/25tC7kcf5x",
            "@Tmckinnin We're likely to see temperatures up to 11°C, light rain and a little wind.  https://t.co/661005cV1n",
            "@Tmckinnin We're looking at temperatures up to 11°C, grey cloud and a little wind.  https://t.co/EPpwBq59rZ",
            "@andrewtathampi We should see temperatures up to 13°C, white cloud and a little wind.  https://t.co/N9RJ7Efav9",
            "@fest64 We should see temperatures as low as 7°C, and light rain.  https://t.co/fxdLFP58Wl",
            "@fest64 We should see temperatures up to 14°C, sunny intervals and a little wind.  https://t.co/rLR5PV7paJ",
            "@fest64 Our forecast shows temperatures up to 14°C, sunny intervals and a little wind.  https://t.co/yUgddS2uYu",
            "@fest64 Our forecast shows temperatures up to 14°C, sunny intervals and a little wind.  https://t.co/CBrIB6sFQm",
            "@mcbdave We're expecting temperatures up to 12°C, light rain and a strong breeze.  https://t.co/oVXb7p9uuT",
            "@Leighannesmiffy We're looking at temperatures up to 16°C, sunny intervals and a little wind.  https://t.co/p1Ah25BvLa",
            "@dazunited We're likely to see temperatures up to 12°C, light rain and a little wind.  https://t.co/hh6JroV3o6",
            "@Tmckinnin We're looking at temperatures up to 12°C, white cloud and a little wind.  https://t.co/X3yWD6nhvq",
            "@Tmckinnin We should see temperatures up to 12°C, white cloud and a little wind.  https://t.co/DTj5Div3mD",
            "@Tmckinnin We're expecting temperatures up to 10°C, heavy rain and a little wind.  https://t.co/OSzPUzIuDg",
            "@Tmckinnin Our forecast shows temperatures up to 11°C, white cloud and a little wind.  https://t.co/XNJ467iEAg",
            "@Tmckinnin We should see temperatures up to 11°C, light rain and a little wind.  https://t.co/rSfZiF0xUe",
            "@meatloaf1333 We're looking at temperatures as low as 7°C, and white cloud.  https://t.co/10jtLzXXP9",
        ]
        for tweet in tweets:
            with self.subTest(tweet=tweet):
                self.assertTrue(WeatherScheduledTask.parse(tweet))

        for tweet in fail_tweets:
            with self.subTest(tweet=tweet):
                self.assertFalse(WeatherScheduledTask.parse(tweet))
